### ISSUE TITLE
Python version requirement

### ISSUE THREAD

**Issue by gwbischof** [LemmyWorld/plemmy#19]
the pyroject.toml file says that this project requires python 3.11.
Is there a specific feature of 3.11 that is needed here?
Python 3.11 is still a pre-release.

**Comment by mgruszkiewicz** [comment]
I don't believe this project use any features from newer Python releases. I also did check using [vermin](https://github.com/netromdk/vermin) and plemmy should work on >=3.7, so we should be fine to lower the required version.
```
Minimum required versions: 3.7
Incompatible versions:     2
```
Also, as far I can tell - Python 3.11 is current stable release and 3.12 is a pre-release?

**Comment by gwbischof** [comment]
Oh yep, I think you are right 3.11 is stable.

**Comment by tjkessler** [comment]
@gwbischof - you're correct, there's really no reason to require 3.11 if Plemmy doesn't use Python's newer features.
@ihyoudou - thanks for testing which Python versions are compatible, and for introducing me to a cool tool!

Setting the minimum requirement to 3.7 makes sense, I'll merge the associated PR.
