### ISSUE TITLE
ListRegistrationApplicationsResponse is invalid

### ISSUE THREAD

**Issue by Pdzly** [LemmyWorld/plemmy#24]
![image](https://github.com/tjkessler/plemmy/assets/34943569/c9884548-1639-4c19-8da5-231caab75ddb)

![image](https://github.com/tjkessler/plemmy/assets/34943569/4e82c2e3-8fac-4ddf-88bb-85726663e6ec)

Backend 0.18.4

Plemmy version: Newest

**Comment by tjkessler** [comment]
Thanks for bringing this up - unfortunately the LemmyHttp documentation hasn't included new attributes for objects recently, so finding these kinds of errors is pretty trial-and-error for now.

Should be fixed as of https://github.com/tjkessler/plemmy/commit/dc0450460b9821e5e63c3d9477fc82c3ce348bb0, with version `0.3.10` containing the change.
