### ISSUE TITLE
Wrong serialisation of unread_only 

### ISSUE THREAD

**Issue by Pdzly** [LemmyWorld/plemmy#26]
httpclientinstance.list_registration_applications(... unread_only=True) gets not correctly formatted to true or false.

Workaround: Falsely put a string "true" or "false" as value instead of the type hinted boolean.

Error:
Query deserialize error: provided string was not `true` or `false`

Code: 
lemmy.list_registration_applications(page=0, unread_only="true")

**Comment by tjkessler** [comment]
@Pdzly let me know if pull https://github.com/LemmyWorld/plemmy/pull/27 fixes your issue!

**Comment by Pdzly** [comment]
Yeah should fix that.

**Comment by tjkessler** [comment]
Fantastic, new version is `0.3.11`.
