### ISSUE TITLE
Unable to list NSFW posts on instances < 0.19

### ISSUE THREAD

**Issue by emilymclean** [LemmyWorld/plemmy#33]
Lemmy instances below version 0.19 require an `auth` parameter to be included in the url to list posts that are NSFW or in an NSFW community. A compatibility mode targeting these older instances would allow clients to work both with older instances, as well as more securely with the new paradigm.

**Comment by Pdzly** [comment]
What plemmy version do you use?

**Comment by Pdzly** [comment]
PLemmy doesnt support <0.19 instance. And this will not change for now.
