### ISSUE TITLE
running get_community not returning community ID

### ISSUE THREAD

**Issue by socphoenix** [LemmyWorld/plemmy#7]
Starting to work on creating a small bot using this but from what I can see on the source this function doesn't return the integer value of the community ID when requested. Am I missing something in how this call works? It only ever responds with the http response code.

**Comment by tjkessler** [comment]
Hi @socphoenix,

All Plemmy functions return a `requests.Response` object. This object contains all data relevant to each API call, which can be accessed with its `.json()` method, returning a dictionary. Here's an [example](https://www.w3schools.com/PYTHON/showpython.asp?filename=demo_requests_response_json) for how access this information.

Hope this helps!

Travis

**Comment by socphoenix** [comment]
Yep! That was what I was missing in the code, thank you!
